### ISSUE TITLE
Couldn't find output file after 30 seconds. Original file may be corrupted.

### ISSUE THREAD

**Issue by librer00t** [derekshreds/Snacks#1]
Hi,

Your app is great btw, simple and has key features, it works great although in my case I access my server by remote desktop, if I start a job with multiple files and folders and then lock the screen it eventually comes up with this error "Couldn't find output file after 30 seconds. Original file may be corrupted." but files are not corrupted, it just go trough all files with same message so when I come back nothing has been done but say if I leave my laptop with the remote desktop session open that wont happen, any suggestions?

thanks

**Comment by derekshreds** [comment]
I’ve never tried running it with a locked screen before. It sounds like it is either losing access to the filesystem or the graphics card when you lock it. Can you tell me which encoder you are using? I’ll try to replicate the issue so I can see what is going on. This particular error usually means ffmpeg wasn’t able to start the conversion process.

**Comment by librer00t** [comment]
> I’ve never tried running it with a locked screen before. It sounds like it is either losing access to the filesystem or the graphics card when you lock it. Can you tell me which encoder you are using? I’ll try to replicate the issue so I can see what is going on. This particular error usually means ffmpeg wasn’t able to start the conversion process.

Currently Nvidia, gtx 1070, today I download v1.0.2 and still same issue, if I disconnect from the remote desktop session it just stops and start displaying the same message ""Couldn't find output file after 30 seconds"

Also a stop and pause button if possible would be nice

**Comment by derekshreds** [comment]
I'm unable to replicate this bug. Keeps encoding just fine with a locked screen for me. Have you tried it with the software encoder? This could be a directory permission problem, a sleeping GPU problem, or a sleeping hard drive problem. The error should generally only appear if ffmpeg wasn't able to even begin a conversion.

**Comment by derekshreds** [comment]
Added in support to retry with software if Remote locks it out of graphics use.
